# Generated by Django 3.0.2 on 2020-04-10 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='meetup_name',
        ),
        migrations.AlterField(
            model_name='person',
            name='status',
            field=models.IntegerField(choices=[(5, 'Contact'), (10, 'Public'), (15, 'Prospective'), (30, 'Member'), (40, 'Committee'), (50, 'Treasurer'), (60, 'Chair')], default=15),
        ),
    ]
