# Generated by Django 3.0 on 2020-04-26 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200410_1322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='cover',
        ),
        migrations.AlterField(
            model_name='person',
            name='status',
            field=models.IntegerField(choices=[(20, 'Member'), (60, 'Manager')], default=20),
        ),
    ]
