# Generated by Django 3.0.2 on 2020-04-18 13:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notice',
            name='author',
        ),
        migrations.RemoveField(
            model_name='event',
            name='attendees',
        ),
        migrations.RemoveField(
            model_name='event',
            name='author',
        ),
        migrations.RemoveField(
            model_name='event',
            name='detail_public',
        ),
        migrations.RemoveField(
            model_name='event',
            name='editable',
        ),
        migrations.RemoveField(
            model_name='event',
            name='hosts',
        ),
        migrations.RemoveField(
            model_name='event',
            name='last_modified',
        ),
        migrations.RemoveField(
            model_name='event',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='event',
            name='photo_cover',
        ),
        migrations.AlterField(
            model_name='event',
            name='e_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Date of the event, in the format "dd/mm/yy", e.g. for 31st December 2020, enter "31/12/20"'),
        ),
        migrations.DeleteModel(
            name='Amendment',
        ),
        migrations.DeleteModel(
            name='Notice',
        ),
    ]
