# Generated by Django 3.0.2 on 2020-04-12 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='site',
            old_name='advert',
            new_name='announcement',
        ),
        migrations.RemoveField(
            model_name='enquiryb',
            name='author',
        ),
        migrations.RemoveField(
            model_name='enquiryb',
            name='title',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='editable',
        ),
        migrations.RemoveField(
            model_name='site',
            name='club',
        ),
        migrations.RemoveField(
            model_name='site',
            name='cover',
        ),
        migrations.RemoveField(
            model_name='site',
            name='criterion4',
        ),
        migrations.RemoveField(
            model_name='site',
            name='criterion5',
        ),
        migrations.RemoveField(
            model_name='site',
            name='criterion6',
        ),
        migrations.RemoveField(
            model_name='site',
            name='daily',
        ),
        migrations.AddField(
            model_name='site',
            name='notice',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Response',
        ),
    ]
