# Generated by Django 3.0 on 2020-04-23 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0004_bookmark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='address',
            field=models.URLField(verbose_name='Address of bookmark'),
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='priority',
            field=models.IntegerField(default=100, verbose_name='Priority of bookmark'),
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='title',
            field=models.TextField(blank=True, null=True, verbose_name='Title of bookmark'),
        ),
        migrations.AlterField(
            model_name='enquiryb',
            name='priority',
            field=models.IntegerField(default=100, verbose_name='Priority of enquiry'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='priority',
            field=models.IntegerField(default=100, verbose_name='Priority of photo'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='title',
            field=models.TextField(blank=True, null=True, verbose_name='Title of photo'),
        ),
    ]
