# Generated by Django 3.0 on 2020-04-24 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0005_auto_20200423_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='address',
            field=models.URLField(default='http://', verbose_name='Address of bookmark'),
        ),
    ]
