# Generated by Django 3.0 on 2020-04-24 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0006_auto_20200424_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='title',
            field=models.TextField(verbose_name='Title of bookmark'),
        ),
    ]
