# Generated by Django 3.0 on 2020-04-25 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0007_auto_20200424_2036'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='upticks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='photo',
            name='upticks',
            field=models.IntegerField(default=0),
        ),
    ]
