# Generated by Django 3.0 on 2020-04-25 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0008_auto_20200425_0133'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='already_liked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='photo',
            name='already_liked',
            field=models.BooleanField(default=False),
        ),
    ]
